### ISSUE TITLE
Partial update의 경우 PUT보다 PATCH를 써야합니다

### ISSUE THREAD

**Issue by Namnamseo** [swsnu/swpp2020-team14#10]
`memo`나 `selected_font`의 수정은 지금 `PUT /api/photo/:photo_id`로 하도록 계획했었는데, 이러면 매번 photo 모델 전체를 보내야 합니다. 무슨 말이냐면

```json
{"a": 1, "b": 2}
```
여기에 `PUT`으로 `{"c": 3}`을 보내면 데이터가

```json
{"c": 3}
```
이렇게 바뀝니다. (정확히는, 이렇게 바뀌도록 구현하는 것이 PUT의 정의입니다.)

`GET`/`POST`/`PUT` 말고 `PATCH`라는 메소드도 있습니다. 처음의 json에 `PATCH`로 `{"c": 3}`을 보내면 데이터가

```json
{"a": 1, "b": 2, "c": 3}
```

이렇게 바뀝니다.

`memo`나 `selected_font`만 수정하고 싶다면 이 기능을 `PATCH` 메소드로 제공하는 게 좋을 것 같습니다..!

**Comment by jaewooklee93** [comment]
네 저도 backend 작성하면서 PUT 부분은 일단 비워뒀는데 PATCH로 변경할 필요가 있을 것 같습니다

**Comment by Jeseong-Jeong** [comment]
좋을 것 같습니다!
