### ISSUE TITLE
User model을 상속 말고 다른 방법으로 처리

### ISSUE THREAD

**Issue by Namnamseo** [swsnu/swpp2020-team14#13]
https://docs.djangoproject.com/en/3.1/topics/auth/customizing/

이 docs에 잘 나와 있습니다.  
proxy model을 만드는 방법은 추가 정보가 필요 없을 때 하는 거라서 저희 목표랑은 조금 다릅니다..!

방법은 두 가지인데
1) Extending the existing `User` model
지금 방식이랑 작동이 비슷할 것 같은데, 기존의 `User` 모델과 one-to-one으로 매칭되는 새로운 모델을 만드는 방법입니다.
장점은 (지금 상태와 비슷하기에) 추가적인 코딩이 적게 들어가고, 단점은 닉네임을 참조할 때 한 단계를 더 거쳐야 합니다. (즉 `request.user.nickname`이 안 되고 `request.user.profile.nickname` 이런 식으로 접근해야 합니다.)
2) Substituting a custom `User` model
새로운 모델을 만들고, django의 기본 인증 모델을 이걸로 대체합니다. (`settings.py`의 `AUTH_USER_MODEL` 설정)
장점은 (1)의 단점, 단점은 (1)의 장점입니다. 보안 부분 (어려운) 메소드는 다 django에서 제공이 되는데, 모델에 들어갈 필드와 `create_user()` 및 `create_superuser()`를 직접 구현해야 합니다.

**Comment by jaewooklee93** [comment]
네 저는 2번 방법으로 하다가 create_user 같은 것이 없어서 일단은 기본제공 `User` 모델을 써보는 것이 어떨까 하였습니다. 아주 다양한 필드가 필요해지면 그때는 custom user model을 정의하여야 할 것 같은데 지금으로서는 `nickname` 필드만 새로 필요한 것이고 이건 이미 있는 `first_name` 필드를 사용하는 것으로 현재로서는 충분히 대응할 수 있을 것 같아서요. 

이건 인터페이스 뒤에서 일어나는 일이라 일단 프론트엔드쪽 구현하고는 별개로 진행해볼 수 있을 것 같습니다

인터페이스는 아래 문서에 조금씩 정리해보겠습니다
https://github.com/swsnu/swpp2020-team14/tree/feature-backend/backend

**Comment by Namnamseo** [comment]
아하 아까 `first_model`이라고 말씀하신게 `first_name`이었군요...!!! 확실히 좋은 방법 같아요 :D

**Comment by Jeseong-Jeong** [comment]
제 의견을 적어보자면 적어주신 장단점을 비교해봤을땐 1번 방법이 더 편리할 것 같아요. 제욱님 아이디어 사용하면 더 간편해질 것 같고요!

**Comment by Namnamseo** [comment]
`first_name`을 사용하도록 하는 커밋 38bcdb0이 `dev`에 merge되었으므로 우선 close합니다.

이후에 `first_name`만으로는 부족해서 다시 customizing이 필요하게 된 경우 그때 re-open하면 될 것 같아요!
