### ISSUE TITLE
backend view에서 PATCH method

### ISSUE THREAD

**Issue by Jeseong-Jeong** [swsnu/swpp2020-team14#17]
#10 을 읽고 backend에서 PATCH method를 구현하던중 막히는 점이 있네요,,
patch로 request를 받는 경우 어떤 field가 들어올지 모르니 backend에서 다룰 때 번거로움이 있는 것 같아요
우선은 if( body.hasAttribute("expected_field") ) 로 구현하고 있는데 이게 patch를 사용하는 적절한 방식인지 의문이 들었습니다.

검색해보니 #9 에서 언급된 seriallizer를 사용하는 답변을 보기도 했습니다.
https://stackoverflow.com/questions/21148039/how-to-make-a-patch-request-using-django-rest-framework/39071384

**Comment by Namnamseo** [comment]
어떤 구현이 좋을 지 모르겠네요... 혹시 코드가 많이 복잡해 지나요..?

그리고 링크에 있는 serializer는 `django-rest-framework`라는 외부 라이브러리에서 쓰는 serializer예요!
이 라이브러리가 워낙 편해서 자주 쓰긴 하더라구요

**Comment by Jeseong-Jeong** [comment]
front에서 patch하는 대상들이 제한 돼 있어서 그렇게 복잡해지진 않을 것 같아요
우선 알겠습니다!
