### ISSUE TITLE
put이나 patch 할 때 주의

### ISSUE THREAD

**Issue by Jeseong-Jeong** [swsnu/swpp2020-team14#18]
put이나 patch를 날릴 때 axios.put("/api/url", payload)로 입력을 하잖아요,
payload를 단순히 {"memo": "my_memo"} 와 같이 만들면 backend에서 empty <query dict>로 인식하는 것 같더라고요.
const payload = new FormData();
payload.append("memo", "my_memo");
이런 식으로 설정해줘야 backend에서 잘 되는 것 같습니다..!

**Comment by Namnamseo** [comment]
제 쪽 작업할 때는 PUT의 FormData는 그 utils.py의 `@prepare_put`을 붙여 줘야 작동했던 것 같은데, 혹시 붙여서 처리하신 건가요? 아니면 다른 방법 있는지 궁금해요..!

**Comment by Jeseong-Jeong** [comment]
네네 prepare_patch를 붙여야 작동해요
'wsgi는 patch가 없다...' 이런식의 에러가 나더라고요
