### ISSUE TITLE
backend에서 `api/report/:photo_id `명령이 필요할 것 같아요.

### ISSUE THREAD

**Issue by Jeseong-Jeong** [swsnu/swpp2020-team14#6]
photo detail에서 접근할 수 있는 analysis page를 만들던중에 report를 불러올 수 있는 api가 없다는 것이 조금 번거롭네요. findings를 불러올 수 있는 api는 존재하질 않는 것 같고요.

`api/report/:photo_id `와 같은 명령으로 
1.photo_id를 가진 photo를 가리키는 findings,
2. photo의 selected font, 
3. photo의 memo
등을 얻을 수 있으면 편리할 것 같아요

**Comment by Jeseong-Jeong** [comment]
아예 selected font, fidings라는 field를 담는 report라는 model을 만드는 것에 대해선 어떻게 생각하세요?

**Comment by jaewooklee93** [comment]
해당 목적으로 현재 있는 API 중에서는 `GET /api/photo/:photo_id/report`를 사용할 수 있을 것 같습니다.

지금은 `id=photo_id`인 Photo에 대한 `list` of `Finding`을 반환하도록 되어 있습니다.

하나의 `Photo`에 여러개의 `Finding`이 존재할 수 있어서 `Report`보다 직관성이 떨어지는 면은 있기는 합니다. 특히 `Finding`이 0개인 상황이 귀찮을수도 있겠네요

만약 위의 API를 써서 photo의 memo를 얻고자 한다면 Finding.photo.memo와 같은 방식으로 접근이 가능합니다

그렇지만 그냥 `GET /api/photo/:photo_id`로 얻는 것이 더 간단할 수도 있어요

**Comment by Namnamseo** [comment]
일단 저는 지금 구현하면서 처음에 계획한 spec이랑 어쩔 수 없이 달라져야 하는 부분은 그냥 달라지도록 두고 있어요..! 그래서 구현하기 편하신 대로 하는게 나을 것 같아요.

다만 제욱님이 말씀하신 것처럼 분석 결과는 `GET /api/photo/:photo_id/report`를 사용해서 받아오고,  
`memo`나 `selected_font`는 `GET /api/photo/:photo_id`로 받아올 수 있습니다.  
그래서 제성님이 말씀하신 문제점을 제가 정확히 이해를 못 한 것 같아요... 조금 더 설명해 주실 수 있을까요?

**Comment by Jeseong-Jeong** [comment]
제욱님 답변에 해결이 되었습니다!
두분 다 감사해요
