### ISSUE TITLE
backend serializer

### ISSUE THREAD

**Issue by jaewooklee93** [swsnu/swpp2020-team14#9]
HW4를 할때는 몰랐는데 django model을 넣으면 저절로 JSON serialization을 수행해주는 함수가 이미 구현되어 있는 것 같습니다. 일단 활용해보고 기능이 잘 작동하는게 확인되면 아래 방식으로 통일하겠습니다

https://docs.djangoproject.com/en/3.1/topics/serialization/

**Comment by Namnamseo** [comment]
이게 편하긴 한데 어떤 API에서는 직접 계산해 줘야 하는 부분들이 있어요.

예를 들면 `is_owner` 필드는 사용자 일치를 비교해야 하고, `is_liked`는 many-to-many table에서 (게시글, 유저) 쌍이 존재하는 지를 확인해 주어야 합니다. 그래서 `DjangoJSONEncoder`에 일임할 수가 없습니다...

다른 방법으로는 모델별로 serializer를 직접 정의할 수는 있습니다. 예를 들어 `FontopiaUserSerializer`, `ArticleSerializer` 등을 만드는 식으로요.

근데 serializer를 만들고 `get()`에서 이걸 반환하는 거랑, 그냥 같은 내용을 `get()`에서 전부 처리하는 거랑 크게 차이가 없게 되는 것 같습니다...
